# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(640, 480)
        Dialog.setMinimumSize(QtCore.QSize(640, 480))
        Dialog.setMaximumSize(QtCore.QSize(640, 480))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 641, 121))
        self.groupBox.setObjectName("groupBox")
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setGeometry(QtCore.QRect(520, 70, 101, 41))
        self.saveButton.setObjectName("saveButton")
        self.answerTextBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.answerTextBrowser.setGeometry(QtCore.QRect(10, 70, 491, 41))
        self.answerTextBrowser.setObjectName("answerTextBrowser")
        self.exampleTextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.exampleTextEdit.setGeometry(QtCore.QRect(10, 20, 491, 41))
        self.exampleTextEdit.setObjectName("exampleTextEdit")
        self.solveButton = QtWidgets.QPushButton(self.groupBox)
        self.solveButton.setGeometry(QtCore.QRect(520, 20, 101, 41))
        self.solveButton.setObjectName("solveButton")
        self.historyTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.historyTextBrowser.setGeometry(QtCore.QRect(10, 120, 621, 341))
        self.historyTextBrowser.setObjectName("historyTextBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.solveButton.setText(_translate("Dialog", "Solve"))
